name: seallapp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - arrow==1.3.0
      - async-timeout==4.0.3
      - attrs==25.3.0
      - babel==2.17.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - bibtexparser==1.4.3
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - deprecated==1.2.18
      - distro==1.9.0
      - dnspython==1.16.0
      - docutils==0.21.2
      - dotenv==0.9.9
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - fake-useragent==2.2.0
      - filelock==3.20.0
      - flask==3.1.1
      - flask-cors==6.0.0
      - flask-pymongo==3.0.1
      - free-proxy==1.1.3
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - google==3.0.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1rc0
      - google-api-python-client==2.172.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-genai==1.19.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - gpt4all==2.8.2
      - greenlet==3.2.4
      - grpcio==1.73.0
      - grpcio-status==1.71.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.35.3
      - idna==3.10
      - imagesize==1.4.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.27
      - langchain-community==0.3.31
      - langchain-core==0.3.79
      - langchain-huggingface==0.3.1
      - langchain-mongodb==0.7.0
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.34
      - lark==1.3.0
      - lxml==6.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mpmath==1.3.0
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openai==1.93.0
      - openpyxl==3.1.5
      - orjson==3.11.3
      - outcome==1.3.0.post0
      - packaging==25.0
      - pandas==2.3.0
      - pillow==11.3.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pycurl==7.45.6
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pymongo==4.15.3
      - pyparsing==3.2.3
      - pypdf==6.1.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scholarly==1.7.11
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - selenium==4.34.0
      - sentence-transformers==5.1.1
      - six==1.17.0
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomli==2.2.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.57.0
      - trio==0.30.0
      - trio-websocket==0.12.2
      - triton==3.4.0
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.4.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - yarl==1.20.1
      - zstandard==0.25.0
prefix: /home/inko/anaconda3/envs/seallapp
